Reword messages to be easier to read.
Melevir/flake8-functions-names pull request #13
Opened 2022-02-08 20:38 UTC by agatti

Messages have been reworded to be both easier to read and without typos/grammar errors.

Original messages featured a few grammar errors and were a bit too verbose, so they have been shortened and cleaned up.  Message codes have not been touched.

2022-02-09 08:36 UTC, Melevir requested changes
Cool, thanks a lot! Could you please also change the phrases in readme?

2022-02-09 16:17 UTC, agatti commented
Done, I changed all instances and the PR should be (correctly) squashed as well.

2022-02-12 08:03 UTC, Melevir commented
Almost there! Fix CI, please.

2022-02-12 16:52 UTC, agatti commented
There you go, should pass flake8 checks now.

2022-02-14 08:26 UTC, Melevir requested changes
Almost there!

2022-02-14 08:26 UTC, Melevir commented on README.md
> +|   FNE001   | Function name that it should return a `bool`, but it returns *actual_type* |
Looks like `says` is missing here.

2023-07-22 17:12 UTC, closed without merging